import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import AuthProvider from "@/services/AuthProvider";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Car-Doctor",
  description: "Generated by Raich uddin",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="doctorTheme" >
      <body className={inter.className}>
        <ToastContainer />
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
